import '../nutrition-hub.css'
import { TODAY, save, state } from './store.js'

const OFF_SEARCH = 'https://world.openfoodfacts.org/cgi/search.pl'

const BASE_FOODS = [
  ['Œuf entier',143,12.6,0.7,9.5],['Blanc de poulet',120,23,0,2.6],['Escalope de dinde',112,24,0,1.5],['Bœuf 5%',137,21,0,5],['Steak haché 10%',176,20,0,10],['Thon au naturel',116,26,0,1],['Saumon',208,20,0,13],['Cabillaud',82,18,0,0.7],
  ['Riz basmati cuit',130,2.7,28,0.3],['Pâtes cuites',157,5.8,30.9,0.9],['Pommes de terre cuites',87,1.9,20,0.1],['Patate douce cuite',90,2,21,0.2],['Pain complet',247,9,41,3.5],['Tortilla blé',312,8,52,8],['Flocons d’avoine',370,13,59,7],
  ['Skyr nature',63,10.8,4,0.2],['Fromage blanc 0%',46,8,4,0.2],['Yaourt grec 0%',59,10,3.6,0.4],['Lait demi-écrémé',46,3.4,4.8,1.5],['Whey protéine',390,78,8,6],
  ['Banane',89,1.1,23,0.3],['Pomme',52,0.3,14,0.2],['Orange',47,0.9,12,0.1],['Fraises',32,0.7,7.7,0.3],['Avocat',160,2,8.5,14.7],
  ['Brocoli',34,2.8,7,0.4],['Haricots verts',31,1.8,7,0.2],['Carottes',41,0.9,10,0.2],['Tomates',18,0.9,3.9,0.2],['Courgettes',17,1.2,3.1,0.3],
  ['Huile d’olive',884,0,0,100],['Beurre de cacahuète',588,25,20,50],['Amandes',579,21,22,50],['Noix',654,15,14,65],['Miel',304,0.3,82,0],
  ['Lentilles cuites',116,9,20,0.4],['Pois chiches cuits',164,8.9,27,2.6],['Haricots rouges cuits',127,8.7,23,0.5],['Tofu ferme',144,17,2.8,8.7]
].map(([name,kcal,protein,carbs,fat],index)=>({id:`base-${index}`,name,kcal,protein,carbs,fat,source:'APEX Base'}))

function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c])}
function num(value){const n=Number(String(value??'').replace(',','.'));return Number.isFinite(n)?n:0}
function uid(prefix){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}
function ensure(){state.recipes=Array.isArray(state.recipes)?state.recipes:[];state.customFoods=Array.isArray(state.customFoods)?state.customFoods:[];state.foodLog=state.foodLog&&typeof state.foodLog==='object'?state.foodLog:{};return state}
function macroFor(food,amount){const f=Math.max(0,num(amount))/100;return {kcal:num(food.kcal)*f,protein:num(food.protein)*f,carbs:num(food.carbs)*f,fat:num(food.fat)*f}}
function addToToday(food,amount=100,extra={}){ensure();const macros=macroFor(food,amount);state.foodLog[TODAY()]=Array.isArray(state.foodLog[TODAY()])?state.foodLog[TODAY()]:[];state.foodLog[TODAY()].push({id:uid('food'),name:food.name,amount:num(amount),per100:{kcal:num(food.kcal),protein:num(food.protein),carbs:num(food.carbs),fat:num(food.fat)},...macros,source:food.source||'APEX',at:new Date().toISOString(),...extra});save({scope:'nutrition'});return macros}

function card(food,index){return `<article class="fh-food"><div><span>${esc(food.brand||food.source||'APEX')}</span><strong>${esc(food.name)}</strong><small>${Math.round(num(food.kcal))} kcal · P ${num(food.protein).toFixed(1)} · G ${num(food.carbs).toFixed(1)} · L ${num(food.fat).toFixed(1)} /100g</small></div><button data-fh-add="${index}">Ajouter</button></article>`}

async function searchOnline(term){
  const url=`${OFF_SEARCH}?search_terms=${encodeURIComponent(term)}&search_simple=1&action=process&json=1&page_size=24&fields=code,product_name,product_name_fr,brands,nutriments`
  const response=await fetch(url,{headers:{Accept:'application/json'}});if(!response.ok) throw new Error('Recherche indisponible')
  const data=await response.json();return (data.products||[]).map((p)=>{const n=p.nutriments||{};return {id:`off-${p.code}`,barcode:p.code,name:p.product_name_fr||p.product_name||'Produit',brand:p.brands||'Open Food Facts',kcal:num(n['energy-kcal_100g']??n['energy-kcal']),protein:num(n.proteins_100g),carbs:num(n.carbohydrates_100g),fat:num(n.fat_100g),source:'Open Food Facts'}}).filter(x=>x.name&&x.kcal>=0)
}

function openAdd(food){
  document.querySelector('.fh-modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="fh-modal"><section><header><div><span>AJOUT RAPIDE</span><h2>${esc(food.name)}</h2></div><button data-fh-close>×</button></header><p>${esc(food.brand||food.source||'APEX')} · ${Math.round(num(food.kcal))} kcal / 100 g</p><label>Quantité consommée (g/ml)<input id="fhAmount" inputmode="decimal" value="100"></label><div class="fh-preview" id="fhPreview"></div><button class="fh-primary" id="fhConfirm">Ajouter à ma journée</button></section></div>`)
  const amount=document.querySelector('#fhAmount'),preview=document.querySelector('#fhPreview');const update=()=>{const m=macroFor(food,amount.value);preview.innerHTML=`<strong>${Math.round(m.kcal)} kcal</strong><span>${m.protein.toFixed(1)} g prot. · ${m.carbs.toFixed(1)} g gluc. · ${m.fat.toFixed(1)} g lip.</span>`};amount.oninput=update;update();document.querySelector('[data-fh-close]').onclick=()=>document.querySelector('.fh-modal')?.remove();document.querySelector('#fhConfirm').onclick=()=>{addToToday(food,amount.value);document.querySelector('.fh-modal')?.remove()}
}

function openRecipeBuilder(){
  ensure();let ingredients=[];document.querySelector('.fh-modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="fh-modal"><section class="fh-recipe-modal"><header><div><span>MES RECETTES</span><h2>Créer une recette</h2></div><button data-fh-close>×</button></header><label>Nom de la recette<input id="frName" placeholder="Ex. Bowl poulet riz"></label><div class="fh-ingredient-form"><input id="frFood" placeholder="Aliment"><input id="frAmount" inputmode="decimal" placeholder="g"><input id="frKcal" inputmode="decimal" placeholder="kcal/100g"><input id="frProtein" inputmode="decimal" placeholder="prot."><input id="frCarbs" inputmode="decimal" placeholder="gluc."><input id="frFat" inputmode="decimal" placeholder="lip."><button id="frAdd">+ ingrédient</button></div><div id="frList" class="fh-recipe-list"></div><div id="frTotals" class="fh-preview"></div><div class="fh-recipe-actions"><button id="frSave" class="fh-primary">Enregistrer la recette</button></div></section></div>`)
  document.querySelector('[data-fh-close]').onclick=()=>document.querySelector('.fh-modal')?.remove()
  const render=()=>{const totals=ingredients.reduce((a,i)=>{const m=macroFor(i,i.amount);for(const k of ['kcal','protein','carbs','fat'])a[k]+=m[k];return a},{kcal:0,protein:0,carbs:0,fat:0});document.querySelector('#frList').innerHTML=ingredients.map((i,idx)=>`<article><div><strong>${esc(i.name)}</strong><small>${i.amount} g</small></div><button data-rm="${idx}">×</button></article>`).join('')||'<p>Aucun ingrédient.</p>';document.querySelector('#frTotals').innerHTML=`<strong>${Math.round(totals.kcal)} kcal</strong><span>${totals.protein.toFixed(1)} g prot. · ${totals.carbs.toFixed(1)} g gluc. · ${totals.fat.toFixed(1)} g lip.</span>`;document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{ingredients.splice(Number(b.dataset.rm),1);render()});return totals}
  document.querySelector('#frAdd').onclick=()=>{const food={name:document.querySelector('#frFood').value.trim(),amount:num(document.querySelector('#frAmount').value),kcal:num(document.querySelector('#frKcal').value),protein:num(document.querySelector('#frProtein').value),carbs:num(document.querySelector('#frCarbs').value),fat:num(document.querySelector('#frFat').value)};if(!food.name||food.amount<=0)return;ingredients.push(food);['frFood','frAmount','frKcal','frProtein','frCarbs','frFat'].forEach(id=>document.querySelector(`#${id}`).value='');render()}
  document.querySelector('#frSave').onclick=()=>{const name=document.querySelector('#frName').value.trim();if(!name||!ingredients.length)return;const totals=render();state.recipes.push({id:uid('recipe'),name,ingredients:[...ingredients],totals,createdAt:new Date().toISOString()});save();document.querySelector('.fh-modal')?.remove();renderHub()};render()
}

function addRecipe(recipe){const servings=1;state.foodLog[TODAY()]=Array.isArray(state.foodLog?.[TODAY()])?state.foodLog[TODAY()]:[];state.foodLog[TODAY()].push({id:uid('recipe-food'),name:recipe.name,amount:servings,...recipe.totals,per100:null,recipeId:recipe.id,source:'Recette APEX',at:new Date().toISOString()});save({scope:'nutrition'})}

function renderHub(){
  if((location.hash||'#home')!=='#nutrition')return;const anchor=document.querySelector('#nutrition-tools-slot-wrap');if(!anchor||document.querySelector('#apex-food-hub'))return;ensure();
  const root=document.createElement('section');root.id='apex-food-hub';root.className='fh';root.innerHTML=`<div class="fh-head"><div><span>APEX FOOD HUB</span><h2>Trouver, créer, enregistrer</h2><p>Recherche un aliment, un produit Aldi/Lidl ou crée ta propre recette.</p></div><button id="fhCreateRecipe">＋ Recette</button></div><div class="fh-search"><input id="fhSearch" placeholder="Ex. œufs, skyr, Milbona, Aldi…"><button id="fhSearchBtn">Rechercher</button></div><div class="fh-filters"><button data-fh-filter="">Base APEX</button><button data-fh-filter="Lidl">Lidl</button><button data-fh-filter="Aldi">Aldi</button><button data-fh-filter="Milbona">Milbona</button><button data-fh-filter="High Protein">High Protein</button></div><div id="fhResults" class="fh-results"></div><div class="fh-recipes"><div class="fh-subhead"><strong>Mes recettes</strong><span>${state.recipes.length}</span></div><div id="fhRecipes"></div></div>`;anchor.before(root)
  let shown=[...state.customFoods,...BASE_FOODS].slice(0,24);const results=root.querySelector('#fhResults');const draw=()=>{results.innerHTML=shown.length?shown.map(card).join(''):'<div class="fh-empty">Aucun résultat.</div>';results.querySelectorAll('[data-fh-add]').forEach(b=>b.onclick=()=>openAdd(shown[Number(b.dataset.fhAdd)]))};draw()
  const recipes=root.querySelector('#fhRecipes');recipes.innerHTML=state.recipes.length?state.recipes.map((r,i)=>`<article class="fh-recipe"><div><strong>${esc(r.name)}</strong><small>${Math.round(num(r.totals?.kcal))} kcal · ${num(r.totals?.protein).toFixed(1)} g prot.</small></div><button data-recipe-add="${i}">Ajouter</button></article>`).join(''):'<div class="fh-empty">Crée ta première recette et réutilise-la ensuite en un geste.</div>';recipes.querySelectorAll('[data-recipe-add]').forEach(b=>b.onclick=()=>addRecipe(state.recipes[Number(b.dataset.recipeAdd)]))
  const run=async(term)=>{const q=term.trim();if(!q){shown=[...state.customFoods,...BASE_FOODS].slice(0,24);draw();return}results.innerHTML='<div class="fh-empty">Recherche dans le catalogue…</div>';const local=[...state.customFoods,...BASE_FOODS].filter(f=>`${f.name} ${f.brand||''}`.toLowerCase().includes(q.toLowerCase()));try{const online=await searchOnline(q);const map=new Map([...local,...online].map(f=>[f.barcode||`${f.name}-${f.brand}`,f]));shown=[...map.values()].slice(0,32)}catch{shown=local}draw()}
  root.querySelector('#fhSearchBtn').onclick=()=>run(root.querySelector('#fhSearch').value);root.querySelector('#fhSearch').addEventListener('keydown',e=>{if(e.key==='Enter')run(e.currentTarget.value)});root.querySelectorAll('[data-fh-filter]').forEach(b=>b.onclick=()=>{root.querySelector('#fhSearch').value=b.dataset.fhFilter;run(b.dataset.fhFilter)});root.querySelector('#fhCreateRecipe').onclick=openRecipeBuilder
}

window.addEventListener('apex:rendered',()=>setTimeout(renderHub,0));window.addEventListener('hashchange',()=>setTimeout(renderHub,0));setTimeout(renderHub,0)
