import '../smart-actions.css'
import { TODAY, save, state } from './store.js'

function number(value){const parsed=Number(String(value??'').replace(',','.'));return Number.isFinite(parsed)?parsed:0}
function esc(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[char])}
function uid(prefix='item'){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function ensureFoodLog(){state.foodLog=state.foodLog&&typeof state.foodLog==='object'?state.foodLog:{};state.foodLog[TODAY()]=Array.isArray(state.foodLog[TODAY()])?state.foodLog[TODAY()]:[];return state.foodLog[TODAY()]}
function recentFoods(){const all=Object.entries(state.foodLog||{}).flatMap(([date,rows])=>(Array.isArray(rows)?rows:[]).map(row=>({...row,date})));all.sort((a,b)=>String(b.at||b.date||'').localeCompare(String(a.at||a.date||'')));const seen=new Set();return all.filter(row=>{const key=row.barcode||row.pantryId||row.name;if(!key||seen.has(key))return false;seen.add(key);return true}).slice(0,8)}
function foodKey(row){return String(row.barcode||row.pantryId||row.name)}
function favorites(){const keys=new Set(state.foodFavorites||[]);return recentFoods().filter(row=>keys.has(foodKey(row)))}
function addRecent(row){const amount=number(row.amount)||100;const per100=row.per100||{kcal:number(row.kcal)/(amount/100||1),protein:number(row.protein)/(amount/100||1),carbs:number(row.carbs)/(amount/100||1),fat:number(row.fat)/(amount/100||1)};const factor=amount/100;ensureFoodLog().push({id:uid('food'),barcode:row.barcode,name:row.name,mealName:state.activeMeal||'Repas',amount,kcal:number(per100.kcal)*factor,protein:number(per100.protein)*factor,carbs:number(per100.carbs)*factor,fat:number(per100.fat)*factor,per100,at:new Date().toISOString()});save({scope:'nutrition'})}

function manualComposerMarkup(){return `<section class="meal-composer simple-composer"><div class="meal-composer__head"><div><span>SAISIE RAPIDE</span><strong>Ajouter manuellement</strong></div></div><div class="meal-composer__meal"><label>Aliment<input id="manualFoodName" autocomplete="off" placeholder="Ex. œufs, riz, poulet…"></label><label>Quantité<input id="manualFoodAmount" inputmode="decimal" placeholder="Ex. 150"></label></div><div class="meal-composer__label"><span>Valeurs pour 100 g / ml</span></div><div class="meal-composer__macros"><label>kcal<input id="manualFoodKcal" inputmode="decimal" placeholder="0"></label><label>Prot.<input id="manualFoodProtein" inputmode="decimal" placeholder="0"></label><label>Gluc.<input id="manualFoodCarbs" inputmode="decimal" placeholder="0"></label><label>Lip.<input id="manualFoodFat" inputmode="decimal" placeholder="0"></label></div><div class="meal-composer__preview" id="manualFoodPreview">Entre l’aliment et sa quantité.</div><button class="meal-composer__save" id="manualFoodSave">Ajouter à ${esc(state.activeMeal||'ce repas')}</button><p class="meal-composer__status" id="manualFoodStatus" hidden></p></section>`}

function bindManualComposer(target){const amount=target.querySelector('#manualFoodAmount'),kcal=target.querySelector('#manualFoodKcal'),protein=target.querySelector('#manualFoodProtein'),carbs=target.querySelector('#manualFoodCarbs'),fat=target.querySelector('#manualFoodFat'),preview=target.querySelector('#manualFoodPreview'),status=target.querySelector('#manualFoodStatus');const update=()=>{const factor=Math.max(0,number(amount?.value))/100;if(!factor){preview.textContent='Entre l’aliment et sa quantité.';return}preview.innerHTML=`<strong>${Math.round(number(kcal?.value)*factor)} kcal</strong><span>${(number(protein?.value)*factor).toFixed(1)} g prot.</span>`};[amount,kcal,protein,carbs,fat].forEach(field=>{if(field)field.oninput=update});target.querySelector('#manualFoodSave').onclick=()=>{const name=target.querySelector('#manualFoodName').value.trim(),qty=Math.max(0,number(amount.value));const per100={kcal:Math.max(0,number(kcal.value)),protein:Math.max(0,number(protein.value)),carbs:Math.max(0,number(carbs.value)),fat:Math.max(0,number(fat.value))};if(!name||qty<=0){status.hidden=false;status.textContent='Indique le nom et la quantité.';return}const factor=qty/100;ensureFoodLog().push({id:uid('food'),name,mealName:state.activeMeal||'Repas',amount:qty,kcal:per100.kcal*factor,protein:per100.protein*factor,carbs:per100.carbs*factor,fat:per100.fat*factor,per100,source:'manual-meal',at:new Date().toISOString()});save({scope:'nutrition'})}}

export function renderQuickFoods(target){if(!target)return;const recents=recentFoods(),favoriteRows=favorites(),shown=[...favoriteRows,...recents.filter(row=>!favoriteRows.some(fav=>foodKey(fav)===foodKey(row)))].slice(0,4);target.innerHTML=`${manualComposerMarkup()}${shown.length?`<section class="quick-foods simple-recents"><div class="quick-foods__head"><strong>Récents</strong><span>Ajouter en un geste</span></div><div class="quick-foods__list">${shown.map((row,index)=>`<article class="quick-food"><div><strong>${esc(row.name)}</strong><small>${Math.round(number(row.kcal))} kcal</small></div><button class="quick-food__add" data-add="${index}">Ajouter</button></article>`).join('')}</div></section>`:''}`;bindManualComposer(target);target.querySelectorAll('[data-add]').forEach(button=>{button.onclick=()=>{addRecent(shown[Number(button.dataset.add)]);button.textContent='Ajouté'}})}
