import './nutrition-scanner.css'

const STORAGE='apex-coach-pro-v1'
const TODAY=()=>new Date().toISOString().slice(0,10)
const OFF='https://world.openfoodfacts.org/api/v2/product/'
let activeControls=null
let activeStream=null

function read(){try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{return {}}}
function write(s){localStorage.setItem(STORAGE,JSON.stringify(s))}
function ensureState(){const s=read();s.pantry=Array.isArray(s.pantry)?s.pantry:[];s.foodLog=s.foodLog&&typeof s.foodLog==='object'?s.foodLog:{};return s}
function esc(v=''){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function n(v,d=1){const x=Number(v);return Number.isFinite(x)?x.toLocaleString('fr-FR',{maximumFractionDigits:d}):'—'}
function stopScanner(){try{activeControls?.stop?.()}catch{};activeControls=null;try{activeStream?.getTracks?.().forEach(t=>t.stop())}catch{};activeStream=null}
function closeSheet(){stopScanner();document.querySelector('.scanner-sheet')?.remove()}
function sheet(title,body){closeSheet();document.body.insertAdjacentHTML('beforeend',`<div class="scanner-sheet"><section class="scanner-panel"><header class="scanner-head"><h2>${esc(title)}</h2><button class="scanner-close" aria-label="Fermer">×</button></header><div class="scanner-body">${body}</div></section></div>`);document.querySelector('.scanner-close').onclick=closeSheet;document.querySelector('.scanner-sheet').addEventListener('click',e=>{if(e.target.classList.contains('scanner-sheet'))closeSheet()})}
function productFromOff(data,barcode){const p=data?.product||{};const nu=p.nutriments||{};return {barcode,name:p.product_name_fr||p.product_name||p.generic_name_fr||p.generic_name||`Produit ${barcode}`,brand:p.brands||'',image:p.image_front_small_url||p.image_front_url||p.image_url||'',kcal:Number(nu['energy-kcal_100g']??nu['energy-kcal']??0)||0,protein:Number(nu.proteins_100g??0)||0,carbs:Number(nu.carbohydrates_100g??0)||0,fat:Number(nu.fat_100g??0)||0,source:'Open Food Facts'}}
async function lookup(barcode){const clean=String(barcode||'').replace(/\D/g,'');if(clean.length<8)throw new Error('Code-barres trop court.');const url=`${OFF}${clean}.json?fields=code,product_name,product_name_fr,generic_name,generic_name_fr,brands,image_front_small_url,image_front_url,image_url,nutriments`;const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Impossible de joindre Open Food Facts.');const data=await r.json();if(data.status!==1||!data.product)throw new Error('Produit introuvable. Tu peux le saisir manuellement.');return productFromOff(data,clean)}
function productMarkup(p){return `<div class="product-result"><div class="product-hero">${p.image?`<img src="${esc(p.image)}" alt="">`:'<div></div>'}<div><h3>${esc(p.name)}</h3><p>${esc(p.brand||'Marque non renseignée')}</p><p>${esc(p.barcode)}</p></div></div><div class="macro-grid"><div><span>kcal</span><strong>${n(p.kcal,0)}</strong></div><div><span>Protéines</span><strong>${n(p.protein)} g</strong></div><div><span>Glucides</span><strong>${n(p.carbs)} g</strong></div><div><span>Lipides</span><strong>${n(p.fat)} g</strong></div></div><div class="product-edit"><label>Quantité achetée<input id="qtyValue" inputmode="decimal" value="1"></label><label>Unité<select id="qtyUnit"><option value="unité">unité</option><option value="g">g</option><option value="ml">ml</option><option value="pack">pack</option></select></label></div><div class="product-actions"><button class="scan-btn secondary" id="editMacros">Modifier les valeurs</button><button class="scan-btn primary" id="saveProduct">Ajouter au stock</button></div><p class="scanner-status">Valeurs affichées pour 100 g/ml. Vérifie l’étiquette si le produit semble incorrect.</p></div>`}
function bindProduct(p){document.querySelector('#saveProduct').onclick=()=>{const s=ensureState();const qty=Number(String(document.querySelector('#qtyValue').value).replace(',','.'))||1;const unit=document.querySelector('#qtyUnit').value;const existing=s.pantry.find(x=>x.barcode===p.barcode);if(existing){existing.qty=(Number(existing.qty)||0)+qty;existing.unit=unit;Object.assign(existing,p)}else s.pantry.push({...p,qty,unit,addedAt:new Date().toISOString()});write(s);renderNutritionEntry();sheet('Produit ajouté',`<div class="scanner-empty"><strong>${esc(p.name)}</strong><br>est maintenant dans ton stock.<div style="margin-top:16px"><button class="scan-btn primary" id="scanAnother">Scanner un autre produit</button></div></div>`);document.querySelector('#scanAnother').onclick=openScanner};document.querySelector('#editMacros').onclick=()=>openManualProduct(p)}
function showProduct(p){sheet('Produit détecté',productMarkup(p));bindProduct(p)}
function openManualProduct(base={}){sheet(base.barcode?'Corriger le produit':'Ajouter un produit',`<div class="product-result"><div class="product-edit" style="grid-template-columns:1fr"><label>Nom<input id="mName" value="${esc(base.name||'')}"></label><label>Code-barres<input id="mCode" inputmode="numeric" value="${esc(base.barcode||'')}"></label></div><div class="macro-grid"><label>kcal / 100 g<input id="mKcal" inputmode="decimal" value="${base.kcal??''}"></label><label>Protéines<input id="mProtein" inputmode="decimal" value="${base.protein??''}"></label><label>Glucides<input id="mCarbs" inputmode="decimal" value="${base.carbs??''}"></label><label>Lipides<input id="mFat" inputmode="decimal" value="${base.fat??''}"></label></div><div class="product-actions"><button class="scan-btn secondary" id="cancelManual">Retour</button><button class="scan-btn primary" id="useManual">Continuer</button></div></div>`);document.querySelector('#cancelManual').onclick=()=>base.barcode?showProduct(base):closeSheet();document.querySelector('#useManual').onclick=()=>{const val=id=>Number(String(document.querySelector(id).value).replace(',','.'))||0;const p={barcode:document.querySelector('#mCode').value.trim()||`manual-${Date.now()}`,name:document.querySelector('#mName').value.trim()||'Produit',brand:base.brand||'',image:base.image||'',kcal:val('#mKcal'),protein:val('#mProtein'),carbs:val('#mCarbs'),fat:val('#mFat'),source:'Saisie manuelle'};showProduct(p)}}
async function decodeWithZXing(video){const mod=await import('https://cdn.jsdelivr.net/npm/@zxing/browser@0.1.5/+esm');const reader=new mod.BrowserMultiFormatReader();activeControls=await reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}},video,(result,error,controls)=>{activeControls=controls;if(result){controls.stop();activeControls=null;handleBarcode(result.getText())}})}
async function openScanner(){sheet('Scanner un produit',`<div class="scanner-camera"><video id="scanVideo" playsinline muted></video><div class="scanner-frame"></div><div class="scanner-line"></div></div><p class="scanner-status" id="scanStatus">Place le code-barres dans le cadre.</p><div class="manual-box"><label>Ou saisir le code-barres<div class="manual-row"><input id="manualBarcode" inputmode="numeric" autocomplete="off" placeholder="Ex. 3017620422003"><button class="scan-btn secondary" id="manualSearch">Chercher</button></div></label></div>`);document.querySelector('#manualSearch').onclick=()=>handleBarcode(document.querySelector('#manualBarcode').value);const video=document.querySelector('#scanVideo');try{if('BarcodeDetector'in window){activeStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});video.srcObject=activeStream;await video.play();const detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e']});let running=true;const loop=async()=>{if(!running||!document.body.contains(video))return;try{const hits=await detector.detect(video);if(hits[0]?.rawValue){running=false;stopScanner();handleBarcode(hits[0].rawValue);return}}catch{};requestAnimationFrame(loop)};loop()}else await decodeWithZXing(video)}catch(e){document.querySelector('#scanStatus').textContent='Caméra indisponible ici. Utilise le code-barres manuel juste en dessous.'}}
async function handleBarcode(code){stopScanner();sheet('Recherche produit','<div class="scanner-empty">Recherche des informations nutritionnelles…</div>');try{showProduct(await lookup(code))}catch(e){sheet('Produit non trouvé',`<div class="scanner-error">${esc(e.message)}</div><div style="margin-top:14px"><button class="scan-btn primary" id="manualCreate">Saisir le produit</button></div>`);document.querySelector('#manualCreate').onclick=()=>openManualProduct({barcode:String(code||'').replace(/\D/g,'')})}}
function openPantry(){const s=ensureState();const items=s.pantry||[];sheet('Mon stock',items.length?`<div class="pantry-list">${items.map((p,i)=>`<article class="pantry-item">${p.image?`<img src="${esc(p.image)}" alt="">`:'<div></div>'}<div><h4>${esc(p.name)}</h4><p>${n(p.qty)} ${esc(p.unit||'unité')} · ${n(p.kcal,0)} kcal / 100 g</p></div><button data-pantry="${i}">Utiliser</button></article>`).join('')}</div>`:'<div class="scanner-empty">Ton stock est vide. Scanne tes courses pour le remplir.</div>');document.querySelectorAll('[data-pantry]').forEach(b=>b.onclick=()=>openConsume(Number(b.dataset.pantry)))}
function openConsume(index){const s=ensureState(),p=s.pantry[index];if(!p)return;sheet('Ajouter à aujourd’hui',`<div class="consume-box"><div class="product-hero">${p.image?`<img src="${esc(p.image)}" alt="">`:'<div></div>'}<div><h3>${esc(p.name)}</h3><p>${n(p.kcal,0)} kcal · ${n(p.protein)} g prot. / 100 g</p></div></div><label>Quantité consommée (g/ml)<input id="consumeAmount" inputmode="decimal" value="100"></label><div class="consume-summary" id="consumeSummary"></div><button class="scan-btn primary" id="saveConsume">Ajouter à ma journée</button></div>`);const input=document.querySelector('#consumeAmount'),sum=document.querySelector('#consumeSummary');const update=()=>{const g=Number(String(input.value).replace(',','.'))||0;const f=g/100;sum.innerHTML=`<strong>${n(p.kcal*f,0)} kcal</strong> · ${n(p.protein*f)} g protéines · ${n(p.carbs*f)} g glucides · ${n(p.fat*f)} g lipides`};input.oninput=update;update();document.querySelector('#saveConsume').onclick=()=>{const s2=ensureState();const g=Number(String(input.value).replace(',','.'))||0;const f=g/100;s2.foodLog[TODAY()]=Array.isArray(s2.foodLog[TODAY()])?s2.foodLog[TODAY()]:[];s2.foodLog[TODAY()].push({barcode:p.barcode,name:p.name,amount:g,kcal:p.kcal*f,protein:p.protein*f,carbs:p.carbs*f,fat:p.fat*f,at:new Date().toISOString()});write(s2);closeSheet();renderNutritionEntry()}}
function dayTotals(){const s=ensureState(),rows=s.foodLog[TODAY()]||[];return rows.reduce((a,x)=>({kcal:a.kcal+(Number(x.kcal)||0),protein:a.protein+(Number(x.protein)||0),carbs:a.carbs+(Number(x.carbs)||0),fat:a.fat+(Number(x.fat)||0)}),{kcal:0,protein:0,carbs:0,fat:0})}
function renderNutritionEntry(){if(location.hash!=='#nutrition')return;const host=document.querySelector('.content');if(!host||document.querySelector('.scanner-entry'))return;const meal=document.querySelector('.meal-card')||document.querySelector('.nutrition-card')||host.children[1];if(!meal)return;const s=ensureState(),t=dayTotals();const html=`<section class="scanner-entry"><div class="scanner-entry__top"><div><h3>Mes aliments</h3><p>Scanne tes courses, garde ton stock à jour et ajoute ce que tu manges sans recopier les macros.</p></div></div><div class="scanner-entry__actions"><button class="scan-btn primary" id="openScanner">Scanner un produit</button><button class="scan-btn secondary" id="openPantry">Voir mon stock</button></div><div class="pantry-summary"><span>${s.pantry.length} produit${s.pantry.length>1?'s':''} en stock</span><strong>Aujourd’hui · ${Math.round(t.kcal)} kcal · ${Math.round(t.protein)} g prot.</strong></div></section>`;meal.insertAdjacentHTML('beforebegin',html);document.querySelector('#openScanner').onclick=openScanner;document.querySelector('#openPantry').onclick=openPantry}
let lock=false;const apply=()=>{if(lock)return;lock=true;requestAnimationFrame(()=>{try{renderNutritionEntry()}finally{lock=false}})};new MutationObserver(apply).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(apply,0));apply()
